# This is a basic workflow to help you get started with Actions

name: Pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: 
    - Chapter15/**
    - .github/workflows/pipeline.yaml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git checkout
        uses: actions/checkout@v2

      - name: az CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: ACR login
        run: az acr login -n handsonakspipeline
        
      
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./Chapter15
          push: true
          tags: handsonakspipeline.azurecr.io/website/website:${{ github.run_number }}
          
  CD:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: CI
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1
        with:
          # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          # Resource Group Name
          resource-group: rg-handsonaks
          # AKS Cluster Name
          cluster-name: handsonaks
      - name: Test kubectl
        run: kubectl get nodes
        
      - name: Helm upgrade
        run: |
          helm upgrade website Chapter15/website --install \
            --set image.repository=handsonakspipeline.azurecr.io/website/website \
            --set image.tag=${{ github.run_number }}

      - name: Get service IP
        run: |
          PUBLICIP=""
          while [ -z $PUBLICIP ]; do
            echo "Waiting for public IP..."
            PUBLICIP=$(kubectl get service website jsonpath='{.status.loadBalancer.ingress[0].ip})
            [ -z "$PUBLICIP" ] && sleep 10
          done
          echo $PUBLICIP
